### ISSUE TITLE
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry X for key 'block_key'")

### ISSUE THREAD

**Issue by deepesch** [dedupeio/dedupe-examples#100]
Hi,

I'm getting integrity while executing ALTER query to add unique index. Can you please help?

`blocking...

creating blocking_map database

creating inverted index

writing blocking map

prepare blocking table. this will probably take a while ...

Traceback (most recent call last):
  File "mysql_example.py", line 371, in <module>
    c.execute("ALTER TABLE blocking_map "
  File "/opt/fingerprints/.venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/opt/fingerprints/.venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/opt/fingerprints/.venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/opt/fingerprints/.venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 379, in _query
    return self._do_query(q)
  File "/opt/fingerprints/.venv/lib/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/opt/fingerprints/.venv/lib/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry '97:B c CL:4-21846152' for key 'block_key'")`

**Comment by AsharAbbas110** [comment]
Hi,

I am also facing the same issue. have you got any work around for this?
