### ISSUE TITLE
ValueError: embedded null character

### ISSUE THREAD

**Issue by deepesch** [dedupeio/dedupe-examples#102]
Hi, I'm getting the following error inconsistently while using mysql_example.py. Could you please help?

ValueError: embedded null character

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "beta_clustering.py", line 242, in <module>
    detecter.prepare_training(temp_d)
  File "/data/fingerprints/ml/lib64/python3.6/site-packages/dedupe/api.py", line 806, in prepare_training
    self.sample(data, sample_size, blocked_proportion, original_length)
  File "/data/fingerprints/ml/lib64/python3.6/site-packages/dedupe/api.py", line 838, in sample
    index_include=examples)
  File "/data/fingerprints/ml/lib64/python3.6/site-packages/dedupe/labeler.py", line 415, in __init__
    index_include)
  File "/data/fingerprints/ml/lib64/python3.6/site-packages/dedupe/labeler.py", line 243, in __init__
    index_data)
  File "/data/fingerprints/ml/lib64/python3.6/site-packages/dedupe/training.py", line 119, in __init__
    self.blocker.indexAll(data)
  File "/data/fingerprints/ml/lib64/python3.6/site-packages/dedupe/blocking.py", line 97, in indexAll
    self.index(unique_fields, field)
  File "/data/fingerprints/ml/lib64/python3.6/site-packages/dedupe/blocking.py", line 64, in index
    index.index(preprocess(doc))
  File "/data/fingerprints/ml/lib64/python3.6/site-packages/dedupe/levenshtein.py", line 15, in index
    Levenshtein_search.add_string(self.index_key, doc)
SystemError: <built-in function add_string> returned a result with an error set

**Comment by fgregg** [comment]
can't reproduce, can you make a smaller test case.
