### ISSUE TITLE
DLL load failed while importing doublemetaphone

### ISSUE THREAD

**Issue by sontata** [dedupeio/dedupe-examples#103]
OS: Windows 10
Python 3.8

Command:
`C:\Users\tanya\PycharmProjects\dedupe-examples\record_linkage_example>python record_linkage_example.py`

Result:
`Traceback (most recent call last):
  File "record_linkage_example.py", line 22, in <module>
    import dedupe
  File "C:\Users\tanya\AppData\Local\Programs\Python\Python38\lib\site-packages\dedupe\__init__.py", line 6, in <module>
    from dedupe._init import *  # noqa
  File "C:\Users\tanya\AppData\Local\Programs\Python\Python38\lib\site-packages\dedupe\_init.py", line 1, in <module>
    from dedupe.api import StaticDedupe, Dedupe  # noqa: F401
  File "C:\Users\tanya\AppData\Local\Programs\Python\Python38\lib\site-packages\dedupe\api.py", line 24, in <module>
    import dedupe.datamodel as datamodel
  File "C:\Users\tanya\AppData\Local\Programs\Python\Python38\lib\site-packages\dedupe\datamodel.py", line 8, in <module>
    import dedupe.variables.base as base
  File "C:\Users\tanya\AppData\Local\Programs\Python\Python38\lib\site-packages\dedupe\variables\base.py", line 1, in <module>
    from dedupe import predicates
  File "C:\Users\tanya\AppData\Local\Programs\Python\Python38\lib\site-packages\dedupe\predicates.py", line 9, in <module>
    from doublemetaphone import doublemetaphone
  File "C:\Users\tanya\AppData\Local\Programs\Python\Python38\lib\site-packages\doublemetaphone\__init__.py", line 1, in <module>
    from .doublemetaphone import doublemetaphone
ImportError: DLL load failed while importing doublemetaphone: The specified module could not be found.`

**Comment by fgregg** [comment]
please try again and let me know if this has been resolved.
