### ISSUE TITLE
ImportError: cannot import name ABC

### ISSUE THREAD

**Issue by vnguyendc** [dedupeio/dedupe-examples#104]
when i run $python csv_example.py I get this error:

```
Traceback (most recent call last):
  File "csv_example.py", line 26, in <module>
    import dedupe
  File "/anaconda3/envs/entity-resolution/lib/python2.7/site-packages/dedupe/__init__.py", line 6, in <module>
    from dedupe._init import *  # noqa
  File "/anaconda3/envs/entity-resolution/lib/python2.7/site-packages/dedupe/_init.py", line 1, in <module>
    from dedupe.api import StaticDedupe, Dedupe  # noqa: F401
  File "/anaconda3/envs/entity-resolution/lib/python2.7/site-packages/dedupe/api.py", line 24, in <module>
    import dedupe.datamodel as datamodel
  File "/anaconda3/envs/entity-resolution/lib/python2.7/site-packages/dedupe/datamodel.py", line 8, in <module>
    import dedupe.variables.base as base
  File "/anaconda3/envs/entity-resolution/lib/python2.7/site-packages/dedupe/variables/base.py", line 1, in <module>
    from dedupe import predicates
  File "/anaconda3/envs/entity-resolution/lib/python2.7/site-packages/dedupe/predicates.py", line 11, in <module>
    import dedupe.tfidf as tfidf
  File "/anaconda3/envs/entity-resolution/lib/python2.7/site-packages/dedupe/tfidf.py", line 6, in <module>
    from .index import Index
  File "/anaconda3/envs/entity-resolution/lib/python2.7/site-packages/dedupe/index.py", line 1, in <module>
    from abc import ABC, abstractmethod
ImportError: cannot import name ABC
```

**Comment by ahsanjaved67** [comment]
Try to change the name of the file or column which is abc.
BR

**Comment by fgregg** [comment]
newer versions of dedupe are python 3 only
