### ISSUE TITLE
The field 'name' is in data_model but not in a record

### ISSUE THREAD

**Issue by tendres** [dedupeio/dedupe-examples#53]
Updating with more info in hopes of finding a resolution...
pgsql_big_dedupe_example_init_db.py runs successfully.

Previous pgsql_big_dedupe_example.py worked , now trying to use the updated example to check out the new intarray stuff.
I understand the error is saying that I don't have the key of 'name in my record - but not sure how to fix this example. 
Anxious to help - pointers please? Receiving the following error in a clean environment:

Traceback (most recent call last):
  File ".../dedupe-examples/pgsql_big_dedupe_example/pgsql_big_dedupe_example.py", line 112, in <module>
    deduper.sample(temp_d, 75000)
  File ".../dedupe/lib/python3.5/site-packages/dedupe/api.py", line 797, in sample
    self._checkData(data)
  File ".../dedupe/lib/python3.5/site-packages/dedupe/api.py", line 817, in _checkData
    self.data_model.check(next(iter(viewvalues(data))))
  File ".../dedupe/lib/python3.5/site-packages/dedupe/datamodel.py", line 122, in check
    "in a record" % field)
ValueError: Records do not line up with data model. The field 'name' is in data_model but not in a record

**Comment by tendres** [comment]
This can be closed - some DATABASE_URL madness with my virtual environment - cured by adding  to project configuration in my IDE.
